auth:
  permissions:
    eav.entity:
      view: View Entity
      list: List Entity
      save: Save Entity
      delete: Delete Entity
    eav.attribute:
      view: View Attribute
      list: List Attribute
      save: Save Attribute
      delete: Delete Attribute
    eav.attribute_group:
      view: View Attribute group
      list: List Attribute group
      save: Save Attribute group
      delete: Delete Attribute group
