swagger:
    info:
        title: EveryWorkflow API
        description: EveryWorkflow API documentation
        contact:
            email: everyworkflow@gmail.com
    servers:
        # - http://localhost:8000
        # - http://localhost:8080
