version: '3'

services:
  fpm:
    # build:
    #   context: php${PHP_VERSION}/fpm
    #   args:
    #     PHP_ENABLE_AMQP: ${PHP_ENABLE_AMQP}
    #     PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
    #     PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    #     PHP_ENABLE_MONGODB: ${PHP_ENABLE_MONGODB}
    image: readymadehost/symfony-dev-docker-php${PHP_VERSION}-fpm:${DOCKER_TAG}
    environment:
        PHP_ENABLE_AMQP: ${PHP_ENABLE_AMQP}
        PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
        PHP_ENABLE_MONGODB: ${PHP_ENABLE_MONGODB}
    ports:
      - ${PHP_FPM_PORT}:9000
    volumes:
      - ./project:/var/www/project
    depends_on:
      - mongodb
      # - redis

  cli:
    # build:
    #   context: php${PHP_VERSION}/cli
    #   args:
    #     NODE_VERSION: ${NODE_VERSION}
    #     PHP_ENABLE_AMQP: ${PHP_ENABLE_AMQP}
    #     PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
    #     PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
    #     PHP_ENABLE_MONGODB: ${PHP_ENABLE_MONGODB}
    image: readymadehost/symfony-dev-docker-php${PHP_VERSION}-cli:${DOCKER_TAG}
    environment:
        PHP_ENABLE_AMQP: ${PHP_ENABLE_AMQP}
        PHP_ENABLE_REDIS: ${PHP_ENABLE_REDIS}
        PHP_ENABLE_XDEBUG: ${PHP_ENABLE_XDEBUG}
        PHP_ENABLE_MONGODB: ${PHP_ENABLE_MONGODB}
    working_dir: /var/www/project
    volumes:
      - ./project:/var/www/project
    depends_on:
      - mongodb
      # - redis

  nginx:
    image: nginx:alpine
    ports:
      - ${NGINX_PORT}:80
    volumes:
      - ./project:/var/www/project
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
    environment:
      - PHP_FPM_PORT=${PHP_FPM_PORT}
    depends_on:
      - fpm

  mongodb:
    image: mongo:${MONGODB_VERSION}
    ports:
      - ${MONGODB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    volumes:
      - ./data/mongodb:/data/db

  # redis:
  #   image: redis:alpine

